//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.12.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from pythia.g4 by ANTLR 4.12.0

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Pythia.Core.Query {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="pythiaParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.12.0")]
[System.CLSCompliant(false)]
public interface IpythiaListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="pythiaParser.query"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterQuery([NotNull] pythiaParser.QueryContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pythiaParser.query"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitQuery([NotNull] pythiaParser.QueryContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pythiaParser.corSet"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCorSet([NotNull] pythiaParser.CorSetContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pythiaParser.corSet"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCorSet([NotNull] pythiaParser.CorSetContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pythiaParser.docSet"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDocSet([NotNull] pythiaParser.DocSetContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pythiaParser.docSet"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDocSet([NotNull] pythiaParser.DocSetContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pythiaParser.docExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDocExpr([NotNull] pythiaParser.DocExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pythiaParser.docExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDocExpr([NotNull] pythiaParser.DocExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pythiaParser.txtExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTxtExpr([NotNull] pythiaParser.TxtExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pythiaParser.txtExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTxtExpr([NotNull] pythiaParser.TxtExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pythiaParser.pair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPair([NotNull] pythiaParser.PairContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pythiaParser.pair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPair([NotNull] pythiaParser.PairContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pythiaParser.spair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSpair([NotNull] pythiaParser.SpairContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pythiaParser.spair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSpair([NotNull] pythiaParser.SpairContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pythiaParser.tpair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTpair([NotNull] pythiaParser.TpairContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pythiaParser.tpair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTpair([NotNull] pythiaParser.TpairContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pythiaParser.locop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLocop([NotNull] pythiaParser.LocopContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pythiaParser.locop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLocop([NotNull] pythiaParser.LocopContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pythiaParser.locExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLocExpr([NotNull] pythiaParser.LocExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pythiaParser.locExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLocExpr([NotNull] pythiaParser.LocExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pythiaParser.locnArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLocnArg([NotNull] pythiaParser.LocnArgContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pythiaParser.locnArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLocnArg([NotNull] pythiaParser.LocnArgContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="pythiaParser.locsArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLocsArg([NotNull] pythiaParser.LocsArgContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="pythiaParser.locsArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLocsArg([NotNull] pythiaParser.LocsArgContext context);
}
} // namespace Pythia.Core.Query
