//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.12.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from pythia.g4 by ANTLR 4.12.0

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace Pythia.Core.Query {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IpythiaListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.12.0")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class pythiaBaseListener : IpythiaListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="pythiaParser.query"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterQuery([NotNull] pythiaParser.QueryContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pythiaParser.query"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitQuery([NotNull] pythiaParser.QueryContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pythiaParser.corSet"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCorSet([NotNull] pythiaParser.CorSetContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pythiaParser.corSet"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCorSet([NotNull] pythiaParser.CorSetContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pythiaParser.docSet"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDocSet([NotNull] pythiaParser.DocSetContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pythiaParser.docSet"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDocSet([NotNull] pythiaParser.DocSetContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pythiaParser.docExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDocExpr([NotNull] pythiaParser.DocExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pythiaParser.docExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDocExpr([NotNull] pythiaParser.DocExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pythiaParser.txtExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTxtExpr([NotNull] pythiaParser.TxtExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pythiaParser.txtExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTxtExpr([NotNull] pythiaParser.TxtExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pythiaParser.pair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPair([NotNull] pythiaParser.PairContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pythiaParser.pair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPair([NotNull] pythiaParser.PairContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pythiaParser.spair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSpair([NotNull] pythiaParser.SpairContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pythiaParser.spair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSpair([NotNull] pythiaParser.SpairContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pythiaParser.tpair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTpair([NotNull] pythiaParser.TpairContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pythiaParser.tpair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTpair([NotNull] pythiaParser.TpairContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pythiaParser.locop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLocop([NotNull] pythiaParser.LocopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pythiaParser.locop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLocop([NotNull] pythiaParser.LocopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pythiaParser.locExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLocExpr([NotNull] pythiaParser.LocExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pythiaParser.locExpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLocExpr([NotNull] pythiaParser.LocExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pythiaParser.locnArg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLocnArg([NotNull] pythiaParser.LocnArgContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pythiaParser.locnArg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLocnArg([NotNull] pythiaParser.LocnArgContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="pythiaParser.locsArg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLocsArg([NotNull] pythiaParser.LocsArgContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="pythiaParser.locsArg"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLocsArg([NotNull] pythiaParser.LocsArgContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace Pythia.Core.Query
