-- profile
INSERT INTO public.profile VALUES ('sample', '{"SourceCollector":{"Id":"source-collector.file","Options":{"IsRecursive":false}},"TextFilters":[{"Id":"text-filter.tei"},{"Id":"text-filter.quotation-mark"}],"AttributeParser":{"Id":"attribute-parser.xml","Options":{"Mappings":["author=/TEI/teiHeader/fileDesc/titleStmt/author","title=/TEI/teiHeader/fileDesc/titleStmt/title","category=/TEI/teiHeader/fileDesc/titleStmt/title/@type","date=/TEI/teiHeader/fileDesc/titleStmt/date","date-value=/TEI/teiHeader/fileDesc/titleStmt/date/@when [N]"]}},"DocSortKeyBuilder":{"Id":"doc-sortkey-builder.standard"},"DocDateValueCalculator":{"Id":"doc-datevalue-calculator.standard","Options":{"Attribute":"date-value"}},"Tokenizer":{"Id":"tokenizer.standard","Options":{"TokenFilters":[{"Id":"token-filter.ita"},{"Id":"token-filter.len-supplier","Options":{"LetterOnly":true}},{"Id":"token-filter.sylc-supplier-lat"}]}},"StructureParsers":[{"Id":"structure-parser.xml","Options":{"RootPath":"/TEI/text/body","Definitions":["div=/div @n head$","p=//p","lg=//lg @n$","l=//l @n$","quote:q:1=//quote","persName:pn=//persName","geogName:gn=//geogName"]},"Filters":[{"Id":"struct-filter.standard"}]},{"Id":"structure-parser.xml-sentence","Options":{"RootPath":"TEI//body","StopTags":["head"]}}],"TextRetriever":{"Id":"text-retriever.file"},"TextMapper":{"Id":"text-mapper.xml","Options":{"RootPath":"/TEI/text/body","MappedPaths":["body/div /@type /@n /head"]}},"TextPicker":{"Id":"text-picker.xml","Options":{"HitOpen":"\u003Chi rend=\u0022hit\u0022\u003E","HitClose":"\u003C/hi\u003E"}},"TextRenderer":{"Id":"text-renderer.liz-html"}}');

-- document
INSERT INTO public.document VALUES (1, 'Catullus', 'carmina', 'c:\users\dfusi\desktop\pythia\sample.xml', 'sample', -54, 'catullus-carmina-A-0054.00', '2021-08-07 09:47:38.445355', NULL);

-- document_attribute
INSERT INTO public.document_attribute VALUES (1, 1, 'category', 'poetry', 0);
INSERT INTO public.document_attribute VALUES (2, 1, 'date', 'I a.C.', 0);
INSERT INTO public.document_attribute VALUES (3, 1, 'date-value', '-54', 1);

-- token
INSERT INTO public.token VALUES (1, NULL, 'ad');
INSERT INTO public.token VALUES (2, NULL, 'arrium');
INSERT INTO public.token VALUES (3, NULL, 'chommoda');
INSERT INTO public.token VALUES (4, NULL, 'dicebat');
INSERT INTO public.token VALUES (5, NULL, 'si');
INSERT INTO public.token VALUES (6, NULL, 'quando');
INSERT INTO public.token VALUES (7, NULL, 'commoda');
INSERT INTO public.token VALUES (8, NULL, 'vellet');
INSERT INTO public.token VALUES (9, NULL, 'dicere');
INSERT INTO public.token VALUES (10, NULL, 'et');
INSERT INTO public.token VALUES (11, NULL, 'insidias');
INSERT INTO public.token VALUES (12, NULL, 'arrius');
INSERT INTO public.token VALUES (13, NULL, 'hinsidias');
INSERT INTO public.token VALUES (14, NULL, 'tum');
INSERT INTO public.token VALUES (15, NULL, 'mirifice');
INSERT INTO public.token VALUES (16, NULL, 'sperabat');
INSERT INTO public.token VALUES (17, NULL, 'se');
INSERT INTO public.token VALUES (18, NULL, 'esse');
INSERT INTO public.token VALUES (19, NULL, 'locutum');
INSERT INTO public.token VALUES (20, NULL, 'cum');
INSERT INTO public.token VALUES (21, NULL, 'quantum');
INSERT INTO public.token VALUES (22, NULL, 'poterat');
INSERT INTO public.token VALUES (23, NULL, 'dixerat');
INSERT INTO public.token VALUES (24, NULL, 'credo');
INSERT INTO public.token VALUES (25, NULL, 'sic');
INSERT INTO public.token VALUES (26, NULL, 'mater');
INSERT INTO public.token VALUES (27, NULL, 'liber');
INSERT INTO public.token VALUES (28, NULL, 'avunculus');
INSERT INTO public.token VALUES (29, NULL, 'eius');
INSERT INTO public.token VALUES (30, NULL, 'maternus');
INSERT INTO public.token VALUES (31, NULL, 'avus');
INSERT INTO public.token VALUES (32, NULL, 'atque');
INSERT INTO public.token VALUES (33, NULL, 'avia');
INSERT INTO public.token VALUES (34, NULL, 'hoc');
INSERT INTO public.token VALUES (35, NULL, 'misso');
INSERT INTO public.token VALUES (36, NULL, 'in');
INSERT INTO public.token VALUES (37, NULL, 'syriam');
INSERT INTO public.token VALUES (38, NULL, 'requierant');
INSERT INTO public.token VALUES (39, NULL, 'omnibus');
INSERT INTO public.token VALUES (40, NULL, 'aures');
INSERT INTO public.token VALUES (41, NULL, 'audibant');
INSERT INTO public.token VALUES (42, NULL, 'eadem');
INSERT INTO public.token VALUES (43, NULL, 'haec');
INSERT INTO public.token VALUES (44, NULL, 'leniter');
INSERT INTO public.token VALUES (45, NULL, 'leviter');
INSERT INTO public.token VALUES (46, NULL, 'nec');
INSERT INTO public.token VALUES (47, NULL, 'sibi');
INSERT INTO public.token VALUES (48, NULL, 'postilla');
INSERT INTO public.token VALUES (49, NULL, 'metuebant');
INSERT INTO public.token VALUES (50, NULL, 'talia');
INSERT INTO public.token VALUES (51, NULL, 'verba');
INSERT INTO public.token VALUES (52, NULL, 'subito');
INSERT INTO public.token VALUES (53, NULL, 'affertur');
INSERT INTO public.token VALUES (54, NULL, 'nuntius');
INSERT INTO public.token VALUES (55, NULL, 'horribilis');
INSERT INTO public.token VALUES (56, NULL, 'ionios');
INSERT INTO public.token VALUES (57, NULL, 'fluctus');
INSERT INTO public.token VALUES (58, NULL, 'postquam');
INSERT INTO public.token VALUES (59, NULL, 'illuc');
INSERT INTO public.token VALUES (60, NULL, 'isset');
INSERT INTO public.token VALUES (61, NULL, 'iam');
INSERT INTO public.token VALUES (62, NULL, 'non');
INSERT INTO public.token VALUES (63, NULL, 'sed');
INSERT INTO public.token VALUES (64, NULL, 'hionios');

-- occurrence
INSERT INTO public.occurrence VALUES (1, 1, 1, 1, 364, 2);
INSERT INTO public.occurrence VALUES (2, 2, 1, 2, 367, 6);
INSERT INTO public.occurrence VALUES (3, 3, 1, 3, 431, 8);
INSERT INTO public.occurrence VALUES (4, 4, 1, 4, 448, 8);
INSERT INTO public.occurrence VALUES (5, 5, 1, 5, 457, 2);
INSERT INTO public.occurrence VALUES (6, 6, 1, 6, 460, 6);
INSERT INTO public.occurrence VALUES (7, 7, 1, 7, 467, 7);
INSERT INTO public.occurrence VALUES (8, 8, 1, 8, 475, 6);
INSERT INTO public.occurrence VALUES (9, 9, 1, 9, 505, 7);
INSERT INTO public.occurrence VALUES (10, 10, 1, 10, 513, 2);
INSERT INTO public.occurrence VALUES (11, 11, 1, 11, 516, 8);
INSERT INTO public.occurrence VALUES (12, 12, 1, 12, 535, 6);
INSERT INTO public.occurrence VALUES (13, 13, 1, 13, 560, 9);
INSERT INTO public.occurrence VALUES (14, 10, 1, 14, 633, 2);
INSERT INTO public.occurrence VALUES (15, 14, 1, 15, 636, 3);
INSERT INTO public.occurrence VALUES (16, 15, 1, 16, 640, 8);
INSERT INTO public.occurrence VALUES (17, 16, 1, 17, 649, 8);
INSERT INTO public.occurrence VALUES (18, 17, 1, 18, 658, 2);
INSERT INTO public.occurrence VALUES (19, 18, 1, 19, 661, 4);
INSERT INTO public.occurrence VALUES (20, 19, 1, 20, 666, 8);
INSERT INTO public.occurrence VALUES (21, 20, 1, 21, 698, 3);
INSERT INTO public.occurrence VALUES (22, 21, 1, 22, 702, 7);
INSERT INTO public.occurrence VALUES (23, 22, 1, 23, 710, 7);
INSERT INTO public.occurrence VALUES (24, 23, 1, 24, 718, 7);
INSERT INTO public.occurrence VALUES (25, 13, 1, 25, 733, 9);
INSERT INTO public.occurrence VALUES (26, 24, 1, 26, 806, 6);
INSERT INTO public.occurrence VALUES (27, 25, 1, 27, 813, 3);
INSERT INTO public.occurrence VALUES (28, 26, 1, 28, 817, 6);
INSERT INTO public.occurrence VALUES (29, 25, 1, 29, 824, 3);
INSERT INTO public.occurrence VALUES (30, 27, 1, 30, 828, 5);
INSERT INTO public.occurrence VALUES (31, 28, 1, 31, 834, 9);
INSERT INTO public.occurrence VALUES (32, 29, 1, 32, 844, 4);
INSERT INTO public.occurrence VALUES (33, 25, 1, 33, 872, 3);
INSERT INTO public.occurrence VALUES (34, 30, 1, 34, 876, 8);
INSERT INTO public.occurrence VALUES (35, 31, 1, 35, 885, 4);
INSERT INTO public.occurrence VALUES (36, 23, 1, 36, 890, 7);
INSERT INTO public.occurrence VALUES (37, 32, 1, 37, 898, 5);
INSERT INTO public.occurrence VALUES (38, 33, 1, 38, 904, 5);
INSERT INTO public.occurrence VALUES (39, 34, 1, 39, 964, 3);
INSERT INTO public.occurrence VALUES (40, 35, 1, 40, 968, 5);
INSERT INTO public.occurrence VALUES (41, 36, 1, 41, 974, 2);
INSERT INTO public.occurrence VALUES (42, 37, 1, 42, 987, 6);
INSERT INTO public.occurrence VALUES (43, 38, 1, 43, 1005, 10);
INSERT INTO public.occurrence VALUES (44, 39, 1, 44, 1016, 7);
INSERT INTO public.occurrence VALUES (45, 40, 1, 45, 1024, 5);
INSERT INTO public.occurrence VALUES (46, 41, 1, 46, 1053, 8);
INSERT INTO public.occurrence VALUES (47, 42, 1, 47, 1062, 5);
INSERT INTO public.occurrence VALUES (48, 43, 1, 48, 1068, 4);
INSERT INTO public.occurrence VALUES (49, 44, 1, 49, 1073, 7);
INSERT INTO public.occurrence VALUES (50, 10, 1, 50, 1081, 2);
INSERT INTO public.occurrence VALUES (51, 45, 1, 51, 1084, 8);
INSERT INTO public.occurrence VALUES (52, 46, 1, 52, 1147, 3);
INSERT INTO public.occurrence VALUES (53, 47, 1, 53, 1151, 4);
INSERT INTO public.occurrence VALUES (54, 48, 1, 54, 1156, 8);
INSERT INTO public.occurrence VALUES (55, 49, 1, 55, 1165, 9);
INSERT INTO public.occurrence VALUES (56, 50, 1, 56, 1175, 5);
INSERT INTO public.occurrence VALUES (57, 51, 1, 57, 1181, 6);
INSERT INTO public.occurrence VALUES (58, 20, 1, 58, 1212, 3);
INSERT INTO public.occurrence VALUES (59, 52, 1, 59, 1216, 6);
INSERT INTO public.occurrence VALUES (60, 53, 1, 60, 1223, 8);
INSERT INTO public.occurrence VALUES (61, 54, 1, 61, 1232, 7);
INSERT INTO public.occurrence VALUES (62, 55, 1, 62, 1240, 11);
INSERT INTO public.occurrence VALUES (63, 56, 1, 63, 1317, 6);
INSERT INTO public.occurrence VALUES (64, 57, 1, 64, 1335, 8);
INSERT INTO public.occurrence VALUES (65, 58, 1, 65, 1344, 8);
INSERT INTO public.occurrence VALUES (66, 59, 1, 66, 1353, 5);
INSERT INTO public.occurrence VALUES (67, 12, 1, 67, 1369, 6);
INSERT INTO public.occurrence VALUES (68, 60, 1, 68, 1387, 6);
INSERT INTO public.occurrence VALUES (69, 61, 1, 69, 1418, 3);
INSERT INTO public.occurrence VALUES (70, 62, 1, 70, 1422, 3);
INSERT INTO public.occurrence VALUES (71, 56, 1, 71, 1436, 6);
INSERT INTO public.occurrence VALUES (72, 18, 1, 72, 1454, 4);
INSERT INTO public.occurrence VALUES (73, 63, 1, 73, 1459, 3);
INSERT INTO public.occurrence VALUES (74, 64, 1, 74, 1480, 7);

-- occurrence.attribute
INSERT INTO public.occurrence_attribute VALUES (1, 1, 'len', '2', 1);
INSERT INTO public.occurrence_attribute VALUES (2, 1, 'sylc', '1', 1);
INSERT INTO public.occurrence_attribute VALUES (3, 1, 'sylc-pos', '0', 1);
INSERT INTO public.occurrence_attribute VALUES (4, 2, 'len', '6', 1);
INSERT INTO public.occurrence_attribute VALUES (5, 2, 'sylc', '3', 1);
INSERT INTO public.occurrence_attribute VALUES (6, 2, 'sylc-pos', '0', 1);
INSERT INTO public.occurrence_attribute VALUES (7, 3, 'len', '8', 1);
INSERT INTO public.occurrence_attribute VALUES (8, 3, 'sylc', '3', 1);
INSERT INTO public.occurrence_attribute VALUES (9, 3, 'sylc-pos', '0', 1);
INSERT INTO public.occurrence_attribute VALUES (10, 4, 'len', '7', 1);
INSERT INTO public.occurrence_attribute VALUES (11, 4, 'sylc', '3', 1);
INSERT INTO public.occurrence_attribute VALUES (12, 4, 'sylc-pos', '0', 1);
INSERT INTO public.occurrence_attribute VALUES (13, 5, 'len', '2', 1);
INSERT INTO public.occurrence_attribute VALUES (14, 5, 'sylc', '1', 1);
INSERT INTO public.occurrence_attribute VALUES (15, 5, 'sylc-pos', '0', 1);
INSERT INTO public.occurrence_attribute VALUES (16, 6, 'len', '6', 1);
INSERT INTO public.occurrence_attribute VALUES (17, 6, 'sylc', '2', 1);
INSERT INTO public.occurrence_attribute VALUES (18, 6, 'sylc-pos', '0', 1);
INSERT INTO public.occurrence_attribute VALUES (19, 7, 'len', '7', 1);
INSERT INTO public.occurrence_attribute VALUES (20, 7, 'sylc', '3', 1);
INSERT INTO public.occurrence_attribute VALUES (21, 7, 'sylc-pos', '0', 1);
INSERT INTO public.occurrence_attribute VALUES (22, 8, 'len', '6', 1);
INSERT INTO public.occurrence_attribute VALUES (23, 8, 'sylc', '2', 1);
INSERT INTO public.occurrence_attribute VALUES (24, 8, 'sylc-pos', '0', 1);
INSERT INTO public.occurrence_attribute VALUES (25, 9, 'len', '6', 1);
INSERT INTO public.occurrence_attribute VALUES (26, 9, 'sylc', '3', 1);
INSERT INTO public.occurrence_attribute VALUES (27, 9, 'sylc-pos', '0', 1);
INSERT INTO public.occurrence_attribute VALUES (28, 10, 'len', '2', 1);
INSERT INTO public.occurrence_attribute VALUES (29, 10, 'sylc', '1', 1);
INSERT INTO public.occurrence_attribute VALUES (30, 10, 'sylc-pos', '0', 1);
INSERT INTO public.occurrence_attribute VALUES (31, 11, 'len', '8', 1);
INSERT INTO public.occurrence_attribute VALUES (32, 11, 'sylc', '4', 1);
INSERT INTO public.occurrence_attribute VALUES (33, 11, 'sylc-pos', '0', 1);
INSERT INTO public.occurrence_attribute VALUES (34, 12, 'len', '6', 1);
INSERT INTO public.occurrence_attribute VALUES (35, 12, 'sylc', '3', 1);
INSERT INTO public.occurrence_attribute VALUES (36, 12, 'sylc-pos', '0', 1);
INSERT INTO public.occurrence_attribute VALUES (37, 13, 'len', '9', 1);
INSERT INTO public.occurrence_attribute VALUES (38, 13, 'sylc', '4', 1);
INSERT INTO public.occurrence_attribute VALUES (39, 13, 'sylc-pos', '0', 1);
INSERT INTO public.occurrence_attribute VALUES (40, 14, 'len', '2', 1);
INSERT INTO public.occurrence_attribute VALUES (41, 14, 'sylc', '1', 1);
INSERT INTO public.occurrence_attribute VALUES (42, 14, 'sylc-pos', '0', 1);
INSERT INTO public.occurrence_attribute VALUES (43, 15, 'len', '3', 1);
INSERT INTO public.occurrence_attribute VALUES (44, 15, 'sylc', '1', 1);
INSERT INTO public.occurrence_attribute VALUES (45, 15, 'sylc-pos', '0', 1);
INSERT INTO public.occurrence_attribute VALUES (46, 16, 'len', '8', 1);
INSERT INTO public.occurrence_attribute VALUES (47, 16, 'sylc', '4', 1);
INSERT INTO public.occurrence_attribute VALUES (48, 16, 'sylc-pos', '0', 1);
INSERT INTO public.occurrence_attribute VALUES (49, 17, 'len', '8', 1);
INSERT INTO public.occurrence_attribute VALUES (50, 17, 'sylc', '3', 1);
INSERT INTO public.occurrence_attribute VALUES (51, 17, 'sylc-pos', '0', 1);
INSERT INTO public.occurrence_attribute VALUES (52, 18, 'len', '2', 1);
INSERT INTO public.occurrence_attribute VALUES (53, 18, 'sylc', '1', 1);
INSERT INTO public.occurrence_attribute VALUES (54, 18, 'sylc-pos', '0', 1);
INSERT INTO public.occurrence_attribute VALUES (55, 19, 'len', '4', 1);
INSERT INTO public.occurrence_attribute VALUES (56, 19, 'sylc', '2', 1);
INSERT INTO public.occurrence_attribute VALUES (57, 19, 'sylc-pos', '0', 1);
INSERT INTO public.occurrence_attribute VALUES (58, 20, 'len', '7', 1);
INSERT INTO public.occurrence_attribute VALUES (59, 20, 'sylc', '3', 1);
INSERT INTO public.occurrence_attribute VALUES (60, 20, 'sylc-pos', '0', 1);
INSERT INTO public.occurrence_attribute VALUES (61, 21, 'len', '3', 1);
INSERT INTO public.occurrence_attribute VALUES (62, 21, 'sylc', '1', 1);
INSERT INTO public.occurrence_attribute VALUES (63, 21, 'sylc-pos', '0', 1);
INSERT INTO public.occurrence_attribute VALUES (64, 22, 'len', '7', 1);
INSERT INTO public.occurrence_attribute VALUES (65, 22, 'sylc', '2', 1);
INSERT INTO public.occurrence_attribute VALUES (66, 22, 'sylc-pos', '0', 1);
INSERT INTO public.occurrence_attribute VALUES (67, 23, 'len', '7', 1);
INSERT INTO public.occurrence_attribute VALUES (68, 23, 'sylc', '3', 1);
INSERT INTO public.occurrence_attribute VALUES (69, 23, 'sylc-pos', '0', 1);
INSERT INTO public.occurrence_attribute VALUES (70, 24, 'len', '7', 1);
INSERT INTO public.occurrence_attribute VALUES (71, 24, 'sylc', '3', 1);
INSERT INTO public.occurrence_attribute VALUES (72, 24, 'sylc-pos', '0', 1);
INSERT INTO public.occurrence_attribute VALUES (73, 25, 'len', '9', 1);
INSERT INTO public.occurrence_attribute VALUES (74, 25, 'sylc', '4', 1);
INSERT INTO public.occurrence_attribute VALUES (75, 25, 'sylc-pos', '0', 1);
INSERT INTO public.occurrence_attribute VALUES (76, 26, 'len', '5', 1);
INSERT INTO public.occurrence_attribute VALUES (77, 26, 'sylc', '2', 1);
INSERT INTO public.occurrence_attribute VALUES (78, 26, 'sylc-pos', '0', 1);
INSERT INTO public.occurrence_attribute VALUES (79, 27, 'len', '3', 1);
INSERT INTO public.occurrence_attribute VALUES (80, 27, 'sylc', '1', 1);
INSERT INTO public.occurrence_attribute VALUES (81, 27, 'sylc-pos', '0', 1);
INSERT INTO public.occurrence_attribute VALUES (82, 28, 'len', '5', 1);
INSERT INTO public.occurrence_attribute VALUES (83, 28, 'sylc', '2', 1);
INSERT INTO public.occurrence_attribute VALUES (84, 28, 'sylc-pos', '0', 1);
INSERT INTO public.occurrence_attribute VALUES (85, 29, 'len', '3', 1);
INSERT INTO public.occurrence_attribute VALUES (86, 29, 'sylc', '1', 1);
INSERT INTO public.occurrence_attribute VALUES (87, 29, 'sylc-pos', '0', 1);
INSERT INTO public.occurrence_attribute VALUES (88, 30, 'len', '5', 1);
INSERT INTO public.occurrence_attribute VALUES (89, 30, 'sylc', '2', 1);
INSERT INTO public.occurrence_attribute VALUES (90, 30, 'sylc-pos', '0', 1);
INSERT INTO public.occurrence_attribute VALUES (91, 31, 'len', '9', 1);
INSERT INTO public.occurrence_attribute VALUES (92, 31, 'sylc', '4', 1);
INSERT INTO public.occurrence_attribute VALUES (93, 31, 'sylc-pos', '0', 1);
INSERT INTO public.occurrence_attribute VALUES (94, 32, 'len', '4', 1);
INSERT INTO public.occurrence_attribute VALUES (95, 32, 'sylc', '2', 1);
INSERT INTO public.occurrence_attribute VALUES (96, 32, 'sylc-pos', '0', 1);
INSERT INTO public.occurrence_attribute VALUES (97, 33, 'len', '3', 1);
INSERT INTO public.occurrence_attribute VALUES (98, 33, 'sylc', '1', 1);
INSERT INTO public.occurrence_attribute VALUES (99, 33, 'sylc-pos', '0', 1);
INSERT INTO public.occurrence_attribute VALUES (100, 34, 'len', '8', 1);
INSERT INTO public.occurrence_attribute VALUES (101, 34, 'sylc', '3', 1);
INSERT INTO public.occurrence_attribute VALUES (102, 34, 'sylc-pos', '0', 1);
INSERT INTO public.occurrence_attribute VALUES (103, 35, 'len', '4', 1);
INSERT INTO public.occurrence_attribute VALUES (104, 35, 'sylc', '2', 1);
INSERT INTO public.occurrence_attribute VALUES (105, 35, 'sylc-pos', '0', 1);
INSERT INTO public.occurrence_attribute VALUES (106, 36, 'len', '7', 1);
INSERT INTO public.occurrence_attribute VALUES (107, 36, 'sylc', '3', 1);
INSERT INTO public.occurrence_attribute VALUES (108, 36, 'sylc-pos', '0', 1);
INSERT INTO public.occurrence_attribute VALUES (109, 37, 'len', '5', 1);
INSERT INTO public.occurrence_attribute VALUES (110, 37, 'sylc', '2', 1);
INSERT INTO public.occurrence_attribute VALUES (111, 37, 'sylc-pos', '0', 1);
INSERT INTO public.occurrence_attribute VALUES (112, 38, 'len', '4', 1);
INSERT INTO public.occurrence_attribute VALUES (113, 38, 'sylc', '3', 1);
INSERT INTO public.occurrence_attribute VALUES (114, 38, 'sylc-pos', '0', 1);
INSERT INTO public.occurrence_attribute VALUES (115, 39, 'len', '3', 1);
INSERT INTO public.occurrence_attribute VALUES (116, 39, 'sylc', '1', 1);
INSERT INTO public.occurrence_attribute VALUES (117, 39, 'sylc-pos', '0', 1);
INSERT INTO public.occurrence_attribute VALUES (118, 40, 'len', '5', 1);
INSERT INTO public.occurrence_attribute VALUES (119, 40, 'sylc', '2', 1);
INSERT INTO public.occurrence_attribute VALUES (120, 40, 'sylc-pos', '0', 1);
INSERT INTO public.occurrence_attribute VALUES (121, 41, 'len', '2', 1);
INSERT INTO public.occurrence_attribute VALUES (122, 41, 'sylc', '1', 1);
INSERT INTO public.occurrence_attribute VALUES (123, 41, 'sylc-pos', '0', 1);
INSERT INTO public.occurrence_attribute VALUES (124, 42, 'len', '6', 1);
INSERT INTO public.occurrence_attribute VALUES (125, 42, 'sylc', '3', 1);
INSERT INTO public.occurrence_attribute VALUES (126, 42, 'sylc-pos', '0', 1);
INSERT INTO public.occurrence_attribute VALUES (127, 43, 'len', '10', 1);
INSERT INTO public.occurrence_attribute VALUES (128, 43, 'sylc', '5', 1);
INSERT INTO public.occurrence_attribute VALUES (129, 43, 'sylc-pos', '0', 1);
INSERT INTO public.occurrence_attribute VALUES (130, 44, 'len', '7', 1);
INSERT INTO public.occurrence_attribute VALUES (131, 44, 'sylc', '3', 1);
INSERT INTO public.occurrence_attribute VALUES (132, 44, 'sylc-pos', '0', 1);
INSERT INTO public.occurrence_attribute VALUES (133, 45, 'len', '5', 1);
INSERT INTO public.occurrence_attribute VALUES (134, 45, 'sylc', '2', 1);
INSERT INTO public.occurrence_attribute VALUES (135, 45, 'sylc-pos', '0', 1);
INSERT INTO public.occurrence_attribute VALUES (136, 46, 'len', '8', 1);
INSERT INTO public.occurrence_attribute VALUES (137, 46, 'sylc', '3', 1);
INSERT INTO public.occurrence_attribute VALUES (138, 46, 'sylc-pos', '0', 1);
INSERT INTO public.occurrence_attribute VALUES (139, 47, 'len', '5', 1);
INSERT INTO public.occurrence_attribute VALUES (140, 47, 'sylc', '3', 1);
INSERT INTO public.occurrence_attribute VALUES (141, 47, 'sylc-pos', '0', 1);
INSERT INTO public.occurrence_attribute VALUES (142, 48, 'len', '4', 1);
INSERT INTO public.occurrence_attribute VALUES (143, 48, 'sylc', '1', 1);
INSERT INTO public.occurrence_attribute VALUES (144, 48, 'sylc-pos', '0', 1);
INSERT INTO public.occurrence_attribute VALUES (145, 49, 'len', '7', 1);
INSERT INTO public.occurrence_attribute VALUES (146, 49, 'sylc', '3', 1);
INSERT INTO public.occurrence_attribute VALUES (147, 49, 'sylc-pos', '0', 1);
INSERT INTO public.occurrence_attribute VALUES (148, 50, 'len', '2', 1);
INSERT INTO public.occurrence_attribute VALUES (149, 50, 'sylc', '1', 1);
INSERT INTO public.occurrence_attribute VALUES (150, 50, 'sylc-pos', '0', 1);
INSERT INTO public.occurrence_attribute VALUES (151, 51, 'len', '7', 1);
INSERT INTO public.occurrence_attribute VALUES (152, 51, 'sylc', '3', 1);
INSERT INTO public.occurrence_attribute VALUES (153, 51, 'sylc-pos', '0', 1);
INSERT INTO public.occurrence_attribute VALUES (154, 52, 'len', '3', 1);
INSERT INTO public.occurrence_attribute VALUES (155, 52, 'sylc', '1', 1);
INSERT INTO public.occurrence_attribute VALUES (156, 52, 'sylc-pos', '0', 1);
INSERT INTO public.occurrence_attribute VALUES (157, 53, 'len', '4', 1);
INSERT INTO public.occurrence_attribute VALUES (158, 53, 'sylc', '2', 1);
INSERT INTO public.occurrence_attribute VALUES (159, 53, 'sylc-pos', '0', 1);
INSERT INTO public.occurrence_attribute VALUES (160, 54, 'len', '8', 1);
INSERT INTO public.occurrence_attribute VALUES (161, 54, 'sylc', '3', 1);
INSERT INTO public.occurrence_attribute VALUES (162, 54, 'sylc-pos', '0', 1);
INSERT INTO public.occurrence_attribute VALUES (163, 55, 'len', '9', 1);
INSERT INTO public.occurrence_attribute VALUES (164, 55, 'sylc', '4', 1);
INSERT INTO public.occurrence_attribute VALUES (165, 55, 'sylc-pos', '0', 1);
INSERT INTO public.occurrence_attribute VALUES (166, 56, 'len', '5', 1);
INSERT INTO public.occurrence_attribute VALUES (167, 56, 'sylc', '3', 1);
INSERT INTO public.occurrence_attribute VALUES (168, 56, 'sylc-pos', '0', 1);
INSERT INTO public.occurrence_attribute VALUES (169, 57, 'len', '5', 1);
INSERT INTO public.occurrence_attribute VALUES (170, 57, 'sylc', '2', 1);
INSERT INTO public.occurrence_attribute VALUES (171, 57, 'sylc-pos', '0', 1);
INSERT INTO public.occurrence_attribute VALUES (172, 58, 'len', '3', 1);
INSERT INTO public.occurrence_attribute VALUES (173, 58, 'sylc', '1', 1);
INSERT INTO public.occurrence_attribute VALUES (174, 58, 'sylc-pos', '0', 1);
INSERT INTO public.occurrence_attribute VALUES (175, 59, 'len', '6', 1);
INSERT INTO public.occurrence_attribute VALUES (176, 59, 'sylc', '3', 1);
INSERT INTO public.occurrence_attribute VALUES (177, 59, 'sylc-pos', '0', 1);
INSERT INTO public.occurrence_attribute VALUES (178, 60, 'len', '8', 1);
INSERT INTO public.occurrence_attribute VALUES (179, 60, 'sylc', '3', 1);
INSERT INTO public.occurrence_attribute VALUES (180, 60, 'sylc-pos', '0', 1);
INSERT INTO public.occurrence_attribute VALUES (181, 61, 'len', '7', 1);
INSERT INTO public.occurrence_attribute VALUES (182, 61, 'sylc', '3', 1);
INSERT INTO public.occurrence_attribute VALUES (183, 61, 'sylc-pos', '0', 1);
INSERT INTO public.occurrence_attribute VALUES (184, 62, 'len', '10', 1);
INSERT INTO public.occurrence_attribute VALUES (185, 62, 'sylc', '4', 1);
INSERT INTO public.occurrence_attribute VALUES (186, 62, 'sylc-pos', '0', 1);
INSERT INTO public.occurrence_attribute VALUES (187, 63, 'len', '6', 1);
INSERT INTO public.occurrence_attribute VALUES (188, 63, 'sylc', '3', 1);
INSERT INTO public.occurrence_attribute VALUES (189, 63, 'sylc-pos', '0', 1);
INSERT INTO public.occurrence_attribute VALUES (190, 64, 'len', '7', 1);
INSERT INTO public.occurrence_attribute VALUES (191, 64, 'sylc', '2', 1);
INSERT INTO public.occurrence_attribute VALUES (192, 64, 'sylc-pos', '0', 1);
INSERT INTO public.occurrence_attribute VALUES (193, 65, 'len', '8', 1);
INSERT INTO public.occurrence_attribute VALUES (194, 65, 'sylc', '2', 1);
INSERT INTO public.occurrence_attribute VALUES (195, 65, 'sylc-pos', '0', 1);
INSERT INTO public.occurrence_attribute VALUES (196, 66, 'len', '5', 1);
INSERT INTO public.occurrence_attribute VALUES (197, 66, 'sylc', '2', 1);
INSERT INTO public.occurrence_attribute VALUES (198, 66, 'sylc-pos', '0', 1);
INSERT INTO public.occurrence_attribute VALUES (199, 67, 'len', '6', 1);
INSERT INTO public.occurrence_attribute VALUES (200, 67, 'sylc', '3', 1);
INSERT INTO public.occurrence_attribute VALUES (201, 67, 'sylc-pos', '0', 1);
INSERT INTO public.occurrence_attribute VALUES (202, 68, 'len', '5', 1);
INSERT INTO public.occurrence_attribute VALUES (203, 68, 'sylc', '2', 1);
INSERT INTO public.occurrence_attribute VALUES (204, 68, 'sylc-pos', '0', 1);
INSERT INTO public.occurrence_attribute VALUES (205, 69, 'len', '3', 1);
INSERT INTO public.occurrence_attribute VALUES (206, 69, 'sylc', '1', 1);
INSERT INTO public.occurrence_attribute VALUES (207, 69, 'sylc-pos', '0', 1);
INSERT INTO public.occurrence_attribute VALUES (208, 70, 'len', '3', 1);
INSERT INTO public.occurrence_attribute VALUES (209, 70, 'sylc', '1', 1);
INSERT INTO public.occurrence_attribute VALUES (210, 70, 'sylc-pos', '0', 1);
INSERT INTO public.occurrence_attribute VALUES (211, 71, 'len', '6', 1);
INSERT INTO public.occurrence_attribute VALUES (212, 71, 'sylc', '3', 1);
INSERT INTO public.occurrence_attribute VALUES (213, 71, 'sylc-pos', '0', 1);
INSERT INTO public.occurrence_attribute VALUES (214, 72, 'len', '4', 1);
INSERT INTO public.occurrence_attribute VALUES (215, 72, 'sylc', '2', 1);
INSERT INTO public.occurrence_attribute VALUES (216, 72, 'sylc-pos', '0', 1);
INSERT INTO public.occurrence_attribute VALUES (217, 73, 'len', '3', 1);
INSERT INTO public.occurrence_attribute VALUES (218, 73, 'sylc', '1', 1);
INSERT INTO public.occurrence_attribute VALUES (219, 73, 'sylc-pos', '0', 1);
INSERT INTO public.occurrence_attribute VALUES (220, 74, 'len', '7', 1);
INSERT INTO public.occurrence_attribute VALUES (221, 74, 'sylc', '4', 1);
INSERT INTO public.occurrence_attribute VALUES (222, 74, 'sylc-pos', '0', 1);
INSERT INTO public.occurrence_attribute VALUES (223, 3, 'q', '1', 0);
INSERT INTO public.occurrence_attribute VALUES (224, 12, 'pn', 'arrius', 0);
INSERT INTO public.occurrence_attribute VALUES (225, 13, 'q', '1', 0);
INSERT INTO public.occurrence_attribute VALUES (226, 25, 'q', '1', 0);
INSERT INTO public.occurrence_attribute VALUES (227, 42, 'gn', 'syriam', 0);
INSERT INTO public.occurrence_attribute VALUES (228, 63, 'gn', 'ionios', 0);
INSERT INTO public.occurrence_attribute VALUES (229, 67, 'pn', 'arrius', 0);
INSERT INTO public.occurrence_attribute VALUES (230, 71, 'gn', 'ionios', 0);
INSERT INTO public.occurrence_attribute VALUES (231, 74, 'q', '1', 0);
INSERT INTO public.occurrence_attribute VALUES (232, 74, 'gn', 'hionios', 0);

-- structure
INSERT INTO public.structure VALUES (1, 1, 1, 74, 'div');
INSERT INTO public.structure VALUES (2, 1, 3, 13, 'lg');
INSERT INTO public.structure VALUES (3, 1, 3, 8, 'l');
INSERT INTO public.structure VALUES (4, 1, 9, 13, 'l');
INSERT INTO public.structure VALUES (5, 1, 14, 25, 'lg');
INSERT INTO public.structure VALUES (6, 1, 14, 20, 'l');
INSERT INTO public.structure VALUES (7, 1, 21, 25, 'l');
INSERT INTO public.structure VALUES (8, 1, 26, 38, 'lg');
INSERT INTO public.structure VALUES (9, 1, 26, 32, 'l');
INSERT INTO public.structure VALUES (10, 1, 33, 38, 'l');
INSERT INTO public.structure VALUES (11, 1, 39, 51, 'lg');
INSERT INTO public.structure VALUES (12, 1, 39, 45, 'l');
INSERT INTO public.structure VALUES (13, 1, 46, 51, 'l');
INSERT INTO public.structure VALUES (14, 1, 52, 62, 'lg');
INSERT INTO public.structure VALUES (15, 1, 52, 57, 'l');
INSERT INTO public.structure VALUES (16, 1, 58, 62, 'l');
INSERT INTO public.structure VALUES (17, 1, 63, 74, 'lg');
INSERT INTO public.structure VALUES (18, 1, 63, 68, 'l');
INSERT INTO public.structure VALUES (19, 1, 69, 74, 'l');
INSERT INTO public.structure VALUES (20, 1, 1, 2, 'sent');
INSERT INTO public.structure VALUES (21, 1, 3, 25, 'sent');
INSERT INTO public.structure VALUES (22, 1, 26, 38, 'sent');
INSERT INTO public.structure VALUES (23, 1, 39, 74, 'sent');

-- structure_attribute
INSERT INTO public.structure_attribute VALUES (1, 1, 'div', '84  ad arrium', 0);
INSERT INTO public.structure_attribute VALUES (2, 2, 'lg', '1', 0);
INSERT INTO public.structure_attribute VALUES (3, 3, 'l', '1', 0);
INSERT INTO public.structure_attribute VALUES (4, 4, 'l', '2', 0);
INSERT INTO public.structure_attribute VALUES (5, 5, 'lg', '2', 0);
INSERT INTO public.structure_attribute VALUES (6, 6, 'l', '3', 0);
INSERT INTO public.structure_attribute VALUES (7, 7, 'l', '4', 0);
INSERT INTO public.structure_attribute VALUES (8, 8, 'lg', '3', 0);
INSERT INTO public.structure_attribute VALUES (9, 9, 'l', '5', 0);
INSERT INTO public.structure_attribute VALUES (10, 10, 'l', '6', 0);
INSERT INTO public.structure_attribute VALUES (11, 11, 'lg', '4', 0);
INSERT INTO public.structure_attribute VALUES (12, 12, 'l', '7', 0);
INSERT INTO public.structure_attribute VALUES (13, 13, 'l', '8', 0);
INSERT INTO public.structure_attribute VALUES (14, 14, 'lg', '5', 0);
INSERT INTO public.structure_attribute VALUES (15, 15, 'l', '9', 0);
INSERT INTO public.structure_attribute VALUES (16, 16, 'l', '10', 0);
INSERT INTO public.structure_attribute VALUES (17, 17, 'lg', '6', 0);
INSERT INTO public.structure_attribute VALUES (18, 18, 'l', '11', 0);
INSERT INTO public.structure_attribute VALUES (19, 19, 'l', '12', 0);

-- document_structure
INSERT INTO public.document_structure VALUES (1, 1, 1);
INSERT INTO public.document_structure VALUES (1, 1, 2);
INSERT INTO public.document_structure VALUES (1, 1, 3);
INSERT INTO public.document_structure VALUES (1, 1, 4);
INSERT INTO public.document_structure VALUES (1, 1, 5);
INSERT INTO public.document_structure VALUES (1, 1, 6);
INSERT INTO public.document_structure VALUES (1, 1, 7);
INSERT INTO public.document_structure VALUES (1, 1, 8);
INSERT INTO public.document_structure VALUES (1, 1, 9);
INSERT INTO public.document_structure VALUES (1, 1, 10);
INSERT INTO public.document_structure VALUES (1, 1, 11);
INSERT INTO public.document_structure VALUES (1, 1, 12);
INSERT INTO public.document_structure VALUES (1, 1, 13);
INSERT INTO public.document_structure VALUES (1, 1, 14);
INSERT INTO public.document_structure VALUES (1, 1, 15);
INSERT INTO public.document_structure VALUES (1, 1, 16);
INSERT INTO public.document_structure VALUES (1, 1, 17);
INSERT INTO public.document_structure VALUES (1, 1, 18);
INSERT INTO public.document_structure VALUES (1, 1, 19);
INSERT INTO public.document_structure VALUES (1, 1, 20);
INSERT INTO public.document_structure VALUES (1, 1, 21);
INSERT INTO public.document_structure VALUES (1, 1, 22);
INSERT INTO public.document_structure VALUES (1, 1, 23);
INSERT INTO public.document_structure VALUES (1, 1, 24);
INSERT INTO public.document_structure VALUES (1, 1, 25);
INSERT INTO public.document_structure VALUES (1, 1, 26);
INSERT INTO public.document_structure VALUES (1, 1, 27);
INSERT INTO public.document_structure VALUES (1, 1, 28);
INSERT INTO public.document_structure VALUES (1, 1, 29);
INSERT INTO public.document_structure VALUES (1, 1, 30);
INSERT INTO public.document_structure VALUES (1, 1, 31);
INSERT INTO public.document_structure VALUES (1, 1, 32);
INSERT INTO public.document_structure VALUES (1, 1, 33);
INSERT INTO public.document_structure VALUES (1, 1, 34);
INSERT INTO public.document_structure VALUES (1, 1, 35);
INSERT INTO public.document_structure VALUES (1, 1, 36);
INSERT INTO public.document_structure VALUES (1, 1, 37);
INSERT INTO public.document_structure VALUES (1, 1, 38);
INSERT INTO public.document_structure VALUES (1, 1, 39);
INSERT INTO public.document_structure VALUES (1, 1, 40);
INSERT INTO public.document_structure VALUES (1, 1, 41);
INSERT INTO public.document_structure VALUES (1, 1, 42);
INSERT INTO public.document_structure VALUES (1, 1, 43);
INSERT INTO public.document_structure VALUES (1, 1, 44);
INSERT INTO public.document_structure VALUES (1, 1, 45);
INSERT INTO public.document_structure VALUES (1, 1, 46);
INSERT INTO public.document_structure VALUES (1, 1, 47);
INSERT INTO public.document_structure VALUES (1, 1, 48);
INSERT INTO public.document_structure VALUES (1, 1, 49);
INSERT INTO public.document_structure VALUES (1, 1, 50);
INSERT INTO public.document_structure VALUES (1, 1, 51);
INSERT INTO public.document_structure VALUES (1, 1, 52);
INSERT INTO public.document_structure VALUES (1, 1, 53);
INSERT INTO public.document_structure VALUES (1, 1, 54);
INSERT INTO public.document_structure VALUES (1, 1, 55);
INSERT INTO public.document_structure VALUES (1, 1, 56);
INSERT INTO public.document_structure VALUES (1, 1, 57);
INSERT INTO public.document_structure VALUES (1, 1, 58);
INSERT INTO public.document_structure VALUES (1, 1, 59);
INSERT INTO public.document_structure VALUES (1, 1, 60);
INSERT INTO public.document_structure VALUES (1, 1, 61);
INSERT INTO public.document_structure VALUES (1, 1, 62);
INSERT INTO public.document_structure VALUES (1, 1, 63);
INSERT INTO public.document_structure VALUES (1, 1, 64);
INSERT INTO public.document_structure VALUES (1, 1, 65);
INSERT INTO public.document_structure VALUES (1, 1, 66);
INSERT INTO public.document_structure VALUES (1, 1, 67);
INSERT INTO public.document_structure VALUES (1, 1, 68);
INSERT INTO public.document_structure VALUES (1, 1, 69);
INSERT INTO public.document_structure VALUES (1, 1, 70);
INSERT INTO public.document_structure VALUES (1, 1, 71);
INSERT INTO public.document_structure VALUES (1, 1, 72);
INSERT INTO public.document_structure VALUES (1, 1, 73);
INSERT INTO public.document_structure VALUES (1, 1, 74);
INSERT INTO public.document_structure VALUES (1, 2, 3);
INSERT INTO public.document_structure VALUES (1, 2, 4);
INSERT INTO public.document_structure VALUES (1, 2, 5);
INSERT INTO public.document_structure VALUES (1, 2, 6);
INSERT INTO public.document_structure VALUES (1, 2, 7);
INSERT INTO public.document_structure VALUES (1, 2, 8);
INSERT INTO public.document_structure VALUES (1, 2, 9);
INSERT INTO public.document_structure VALUES (1, 2, 10);
INSERT INTO public.document_structure VALUES (1, 2, 11);
INSERT INTO public.document_structure VALUES (1, 2, 12);
INSERT INTO public.document_structure VALUES (1, 2, 13);
INSERT INTO public.document_structure VALUES (1, 3, 3);
INSERT INTO public.document_structure VALUES (1, 3, 4);
INSERT INTO public.document_structure VALUES (1, 3, 5);
INSERT INTO public.document_structure VALUES (1, 3, 6);
INSERT INTO public.document_structure VALUES (1, 3, 7);
INSERT INTO public.document_structure VALUES (1, 3, 8);
INSERT INTO public.document_structure VALUES (1, 4, 9);
INSERT INTO public.document_structure VALUES (1, 4, 10);
INSERT INTO public.document_structure VALUES (1, 4, 11);
INSERT INTO public.document_structure VALUES (1, 4, 12);
INSERT INTO public.document_structure VALUES (1, 4, 13);
INSERT INTO public.document_structure VALUES (1, 5, 14);
INSERT INTO public.document_structure VALUES (1, 5, 15);
INSERT INTO public.document_structure VALUES (1, 5, 16);
INSERT INTO public.document_structure VALUES (1, 5, 17);
INSERT INTO public.document_structure VALUES (1, 5, 18);
INSERT INTO public.document_structure VALUES (1, 5, 19);
INSERT INTO public.document_structure VALUES (1, 5, 20);
INSERT INTO public.document_structure VALUES (1, 5, 21);
INSERT INTO public.document_structure VALUES (1, 5, 22);
INSERT INTO public.document_structure VALUES (1, 5, 23);
INSERT INTO public.document_structure VALUES (1, 5, 24);
INSERT INTO public.document_structure VALUES (1, 5, 25);
INSERT INTO public.document_structure VALUES (1, 6, 14);
INSERT INTO public.document_structure VALUES (1, 6, 15);
INSERT INTO public.document_structure VALUES (1, 6, 16);
INSERT INTO public.document_structure VALUES (1, 6, 17);
INSERT INTO public.document_structure VALUES (1, 6, 18);
INSERT INTO public.document_structure VALUES (1, 6, 19);
INSERT INTO public.document_structure VALUES (1, 6, 20);
INSERT INTO public.document_structure VALUES (1, 7, 21);
INSERT INTO public.document_structure VALUES (1, 7, 22);
INSERT INTO public.document_structure VALUES (1, 7, 23);
INSERT INTO public.document_structure VALUES (1, 7, 24);
INSERT INTO public.document_structure VALUES (1, 7, 25);
INSERT INTO public.document_structure VALUES (1, 8, 26);
INSERT INTO public.document_structure VALUES (1, 8, 27);
INSERT INTO public.document_structure VALUES (1, 8, 28);
INSERT INTO public.document_structure VALUES (1, 8, 29);
INSERT INTO public.document_structure VALUES (1, 8, 30);
INSERT INTO public.document_structure VALUES (1, 8, 31);
INSERT INTO public.document_structure VALUES (1, 8, 32);
INSERT INTO public.document_structure VALUES (1, 8, 33);
INSERT INTO public.document_structure VALUES (1, 8, 34);
INSERT INTO public.document_structure VALUES (1, 8, 35);
INSERT INTO public.document_structure VALUES (1, 8, 36);
INSERT INTO public.document_structure VALUES (1, 8, 37);
INSERT INTO public.document_structure VALUES (1, 8, 38);
INSERT INTO public.document_structure VALUES (1, 9, 26);
INSERT INTO public.document_structure VALUES (1, 9, 27);
INSERT INTO public.document_structure VALUES (1, 9, 28);
INSERT INTO public.document_structure VALUES (1, 9, 29);
INSERT INTO public.document_structure VALUES (1, 9, 30);
INSERT INTO public.document_structure VALUES (1, 9, 31);
INSERT INTO public.document_structure VALUES (1, 9, 32);
INSERT INTO public.document_structure VALUES (1, 10, 33);
INSERT INTO public.document_structure VALUES (1, 10, 34);
INSERT INTO public.document_structure VALUES (1, 10, 35);
INSERT INTO public.document_structure VALUES (1, 10, 36);
INSERT INTO public.document_structure VALUES (1, 10, 37);
INSERT INTO public.document_structure VALUES (1, 10, 38);
INSERT INTO public.document_structure VALUES (1, 11, 39);
INSERT INTO public.document_structure VALUES (1, 11, 40);
INSERT INTO public.document_structure VALUES (1, 11, 41);
INSERT INTO public.document_structure VALUES (1, 11, 42);
INSERT INTO public.document_structure VALUES (1, 11, 43);
INSERT INTO public.document_structure VALUES (1, 11, 44);
INSERT INTO public.document_structure VALUES (1, 11, 45);
INSERT INTO public.document_structure VALUES (1, 11, 46);
INSERT INTO public.document_structure VALUES (1, 11, 47);
INSERT INTO public.document_structure VALUES (1, 11, 48);
INSERT INTO public.document_structure VALUES (1, 11, 49);
INSERT INTO public.document_structure VALUES (1, 11, 50);
INSERT INTO public.document_structure VALUES (1, 11, 51);
INSERT INTO public.document_structure VALUES (1, 12, 39);
INSERT INTO public.document_structure VALUES (1, 12, 40);
INSERT INTO public.document_structure VALUES (1, 12, 41);
INSERT INTO public.document_structure VALUES (1, 12, 42);
INSERT INTO public.document_structure VALUES (1, 12, 43);
INSERT INTO public.document_structure VALUES (1, 12, 44);
INSERT INTO public.document_structure VALUES (1, 12, 45);
INSERT INTO public.document_structure VALUES (1, 13, 46);
INSERT INTO public.document_structure VALUES (1, 13, 47);
INSERT INTO public.document_structure VALUES (1, 13, 48);
INSERT INTO public.document_structure VALUES (1, 13, 49);
INSERT INTO public.document_structure VALUES (1, 13, 50);
INSERT INTO public.document_structure VALUES (1, 13, 51);
INSERT INTO public.document_structure VALUES (1, 14, 52);
INSERT INTO public.document_structure VALUES (1, 14, 53);
INSERT INTO public.document_structure VALUES (1, 14, 54);
INSERT INTO public.document_structure VALUES (1, 14, 55);
INSERT INTO public.document_structure VALUES (1, 14, 56);
INSERT INTO public.document_structure VALUES (1, 14, 57);
INSERT INTO public.document_structure VALUES (1, 14, 58);
INSERT INTO public.document_structure VALUES (1, 14, 59);
INSERT INTO public.document_structure VALUES (1, 14, 60);
INSERT INTO public.document_structure VALUES (1, 14, 61);
INSERT INTO public.document_structure VALUES (1, 14, 62);
INSERT INTO public.document_structure VALUES (1, 15, 52);
INSERT INTO public.document_structure VALUES (1, 15, 53);
INSERT INTO public.document_structure VALUES (1, 15, 54);
INSERT INTO public.document_structure VALUES (1, 15, 55);
INSERT INTO public.document_structure VALUES (1, 15, 56);
INSERT INTO public.document_structure VALUES (1, 15, 57);
INSERT INTO public.document_structure VALUES (1, 16, 58);
INSERT INTO public.document_structure VALUES (1, 16, 59);
INSERT INTO public.document_structure VALUES (1, 16, 60);
INSERT INTO public.document_structure VALUES (1, 16, 61);
INSERT INTO public.document_structure VALUES (1, 16, 62);
INSERT INTO public.document_structure VALUES (1, 17, 63);
INSERT INTO public.document_structure VALUES (1, 17, 64);
INSERT INTO public.document_structure VALUES (1, 17, 65);
INSERT INTO public.document_structure VALUES (1, 17, 66);
INSERT INTO public.document_structure VALUES (1, 17, 67);
INSERT INTO public.document_structure VALUES (1, 17, 68);
INSERT INTO public.document_structure VALUES (1, 17, 69);
INSERT INTO public.document_structure VALUES (1, 17, 70);
INSERT INTO public.document_structure VALUES (1, 17, 71);
INSERT INTO public.document_structure VALUES (1, 17, 72);
INSERT INTO public.document_structure VALUES (1, 17, 73);
INSERT INTO public.document_structure VALUES (1, 17, 74);
INSERT INTO public.document_structure VALUES (1, 18, 63);
INSERT INTO public.document_structure VALUES (1, 18, 64);
INSERT INTO public.document_structure VALUES (1, 18, 65);
INSERT INTO public.document_structure VALUES (1, 18, 66);
INSERT INTO public.document_structure VALUES (1, 18, 67);
INSERT INTO public.document_structure VALUES (1, 18, 68);
INSERT INTO public.document_structure VALUES (1, 19, 69);
INSERT INTO public.document_structure VALUES (1, 19, 70);
INSERT INTO public.document_structure VALUES (1, 19, 71);
INSERT INTO public.document_structure VALUES (1, 19, 72);
INSERT INTO public.document_structure VALUES (1, 19, 73);
INSERT INTO public.document_structure VALUES (1, 19, 74);
INSERT INTO public.document_structure VALUES (1, 20, 1);
INSERT INTO public.document_structure VALUES (1, 20, 2);
INSERT INTO public.document_structure VALUES (1, 21, 3);
INSERT INTO public.document_structure VALUES (1, 21, 4);
INSERT INTO public.document_structure VALUES (1, 21, 5);
INSERT INTO public.document_structure VALUES (1, 21, 6);
INSERT INTO public.document_structure VALUES (1, 21, 7);
INSERT INTO public.document_structure VALUES (1, 21, 8);
INSERT INTO public.document_structure VALUES (1, 21, 9);
INSERT INTO public.document_structure VALUES (1, 21, 10);
INSERT INTO public.document_structure VALUES (1, 21, 11);
INSERT INTO public.document_structure VALUES (1, 21, 12);
INSERT INTO public.document_structure VALUES (1, 21, 13);
INSERT INTO public.document_structure VALUES (1, 21, 14);
INSERT INTO public.document_structure VALUES (1, 21, 15);
INSERT INTO public.document_structure VALUES (1, 21, 16);
INSERT INTO public.document_structure VALUES (1, 21, 17);
INSERT INTO public.document_structure VALUES (1, 21, 18);
INSERT INTO public.document_structure VALUES (1, 21, 19);
INSERT INTO public.document_structure VALUES (1, 21, 20);
INSERT INTO public.document_structure VALUES (1, 21, 21);
INSERT INTO public.document_structure VALUES (1, 21, 22);
INSERT INTO public.document_structure VALUES (1, 21, 23);
INSERT INTO public.document_structure VALUES (1, 21, 24);
INSERT INTO public.document_structure VALUES (1, 21, 25);
INSERT INTO public.document_structure VALUES (1, 22, 26);
INSERT INTO public.document_structure VALUES (1, 22, 27);
INSERT INTO public.document_structure VALUES (1, 22, 28);
INSERT INTO public.document_structure VALUES (1, 22, 29);
INSERT INTO public.document_structure VALUES (1, 22, 30);
INSERT INTO public.document_structure VALUES (1, 22, 31);
INSERT INTO public.document_structure VALUES (1, 22, 32);
INSERT INTO public.document_structure VALUES (1, 22, 33);
INSERT INTO public.document_structure VALUES (1, 22, 34);
INSERT INTO public.document_structure VALUES (1, 22, 35);
INSERT INTO public.document_structure VALUES (1, 22, 36);
INSERT INTO public.document_structure VALUES (1, 22, 37);
INSERT INTO public.document_structure VALUES (1, 22, 38);
INSERT INTO public.document_structure VALUES (1, 23, 39);
INSERT INTO public.document_structure VALUES (1, 23, 40);
INSERT INTO public.document_structure VALUES (1, 23, 41);
INSERT INTO public.document_structure VALUES (1, 23, 42);
INSERT INTO public.document_structure VALUES (1, 23, 43);
INSERT INTO public.document_structure VALUES (1, 23, 44);
INSERT INTO public.document_structure VALUES (1, 23, 45);
INSERT INTO public.document_structure VALUES (1, 23, 46);
INSERT INTO public.document_structure VALUES (1, 23, 47);
INSERT INTO public.document_structure VALUES (1, 23, 48);
INSERT INTO public.document_structure VALUES (1, 23, 49);
INSERT INTO public.document_structure VALUES (1, 23, 50);
INSERT INTO public.document_structure VALUES (1, 23, 51);
INSERT INTO public.document_structure VALUES (1, 23, 52);
INSERT INTO public.document_structure VALUES (1, 23, 53);
INSERT INTO public.document_structure VALUES (1, 23, 54);
INSERT INTO public.document_structure VALUES (1, 23, 55);
INSERT INTO public.document_structure VALUES (1, 23, 56);
INSERT INTO public.document_structure VALUES (1, 23, 57);
INSERT INTO public.document_structure VALUES (1, 23, 58);
INSERT INTO public.document_structure VALUES (1, 23, 59);
INSERT INTO public.document_structure VALUES (1, 23, 60);
INSERT INTO public.document_structure VALUES (1, 23, 61);
INSERT INTO public.document_structure VALUES (1, 23, 62);
INSERT INTO public.document_structure VALUES (1, 23, 63);
INSERT INTO public.document_structure VALUES (1, 23, 64);
INSERT INTO public.document_structure VALUES (1, 23, 65);
INSERT INTO public.document_structure VALUES (1, 23, 66);
INSERT INTO public.document_structure VALUES (1, 23, 67);
INSERT INTO public.document_structure VALUES (1, 23, 68);
INSERT INTO public.document_structure VALUES (1, 23, 69);
INSERT INTO public.document_structure VALUES (1, 23, 70);
INSERT INTO public.document_structure VALUES (1, 23, 71);
INSERT INTO public.document_structure VALUES (1, 23, 72);
INSERT INTO public.document_structure VALUES (1, 23, 73);
INSERT INTO public.document_structure VALUES (1, 23, 74);
