//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pythia.Sql.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pythia.Sql.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0},{1}: invalid numeric argument in operator {2}: &quot;{3}&quot;.
        /// </summary>
        internal static string ArgopInvalidNArg {
            get {
                return ResourceManager.GetString("ArgopInvalidNArg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0},{1}: invalid argument pair for operator {2}: expected name=value or name*=value, found {3}.
        /// </summary>
        internal static string ArgopInvalidPair {
            get {
                return ResourceManager.GetString("ArgopInvalidPair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0},{1}: missing argument(s) for operator {2}: expected {3}, found {4}.
        /// </summary>
        internal static string ArgopMissingArgs {
            get {
                return ResourceManager.GetString("ArgopMissingArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0},{1}: in operator {2} argument NE ({3}) is greater than argument ME ({4}).
        /// </summary>
        internal static string ArgopNEGreaterThanME {
            get {
                return ResourceManager.GetString("ArgopNEGreaterThanME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0},{1}: in operator {2} argument N ({3}) is greater than argument M ({4}).
        /// </summary>
        internal static string ArgopNGreaterThanM {
            get {
                return ResourceManager.GetString("ArgopNGreaterThanM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0},{1}: no non-empty argument(s) for operator {2}: expected {3}, found {4}.
        /// </summary>
        internal static string ArgopNoArgs {
            get {
                return ResourceManager.GetString("ArgopNoArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0},{1}: in operator {2} argument NS ({3}) is greater than argument MS ({4}).
        /// </summary>
        internal static string ArgopNSGreaterThanMS {
            get {
                return ResourceManager.GetString("ArgopNSGreaterThanMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0},{1}: argument S is not allowed on negative collocations for {2} in &quot;{3}&quot;.
        /// </summary>
        internal static string ArgopSWithNot {
            get {
                return ResourceManager.GetString("ArgopSWithNot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0},{1}: too many argument(s) for operator {2}: expected {3}, found {4}.
        /// </summary>
        internal static string ArgopTooManyArgs {
            get {
                return ResourceManager.GetString("ArgopTooManyArgs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0},{1}: INSIDE operator cannot target a token: &quot;{2}&quot;.
        /// </summary>
        internal static string InsideWithToken {
            get {
                return ResourceManager.GetString("InsideWithToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0},{1}: invalid short pair &quot;{2}&quot;: short pairs cannot be used with privileged attributes.
        /// </summary>
        internal static string InvalidShortPair {
            get {
                return ResourceManager.GetString("InvalidShortPair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0},{1}: missing pair&apos;s value for &quot;{2}&quot;.
        /// </summary>
        internal static string NoPairValue {
            get {
                return ResourceManager.GetString("NoPairValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0},}1|: missing previous structure pair for &quot;{2}&quot;.
        /// </summary>
        internal static string NoPrevStructurePair {
            get {
                return ResourceManager.GetString("NoPrevStructurePair", resourceCulture);
            }
        }
    }
}
