@HostAddress = http://localhost:5000

### Login

POST {{HostAddress}}/api/auth/login
Content-Type: application/json

{
  "username": "zeus",
  "password": "P4ss-W0rd!"
}

### Stats

GET {{HostAddress}}/api/stats

### Search

GET {{HostAddress}}/api/search?query=%5Bvalue%3D%22pregiudiziale%22%5D

### Export Search

GET {{HostAddress}}/api/search/csv?query=%5Bvalue%3D%22pregiudiziale%22%5D
